### ISSUE TITLE
Scaffold subset of tables (on very...very large databases)

### ISSUE THREAD

**Issue by jschneidereit** [hherzl/CatFactory.Dapper#1]
The entity framework tools have the concept of scaffolding the tables you actually need in your database.
This is very helpful when you only want the database context to provide CRUD operations on a subset of the tables. 

Would it be possible to add this feature?
I'd be willing to submit a PR as well if you're interested and could point me in the right direction!

This is what the entity framework scaffolding looks like:
```powershell
$tables = @('Company', 'User', 'Address')
Scaffold-DbContext $connstring Microsoft.EntityFrameworkCore.SqlServer -OutputDir 'DataAccess/Models' -Tables $tables -Force
```

**Comment by hherzl** [comment]
Hi, thank you so much for your message.

In fact you can do that importing specific tables from database:

var database = SqlServerDatabaseFactory
 .ImportTables("server=(local);database=Store;integrated security=yes;", "FirstTable", "SecondTable");

Please let me know if this is useful.

Regards

**Comment by jschneidereit** [comment]
Ah, I missed that overload, thank you!
