### ISSUE TITLE
First letter lower case at Constructor

### ISSUE THREAD

**Issue by GetDragon** [hherzl/CatFactory.Dapper#4]
`public ObrNivelAcceso(short? nIVELACCESOID)
{
   NivelAccesoId = nIVELACCESOID;
		}`

Hi man... the first letter of the parameter is in lower case... i fork this project for find this.

Nice job!

**Comment by hherzl** [comment]
Hi.

Which file?

I have searched but I didn't found any constructor with that name.

**Comment by GetDragon** [comment]
Ma mistake... sorry... i mean, the code generated looks like.... my table and fieldname is UPPERCASE... for some reason the firs letter appear in lower case.

**Comment by hherzl** [comment]
I get your point.

Let me add a test for solution.

Thank you so much for your feedback.

Regards

**Comment by hherzl** [comment]
Hi, get last version and try again, let me know if you have any issues.

Regards
