### ISSUE TITLE
Wrong Mapping

### ISSUE THREAD

**Issue by GetDragon** [hherzl/CatFactory.Dapper#5]
Hi again...

I implement the layers generated for CatFactory in my project, but the entitys name and properties are renamed en capital case i think... and the SQL generated not mapping whith the entity.

`

            // Create sql statement
            query.Append(" SELECT ");
            query.Append("  [OBRA_ID_CONTENIDO] ObraIdContenido, ");
            query.Append("  [OBRA_TITULO] ObraTitulo, ");
            query.Append("  [OBRA_ES_RECOMENDADO] ObraEsRecomendado, ");
            query.Append("  [OBRA_ORDEN_RECOMENDADO] ObraOrdenRecomendado, ");
            query.Append("  [OBRA_ES_VISIBLE] ObraEsVisible, ");
            query.Append("  [FORMATO] Formato, ");
            query.Append("  [PORTADA] Portada, ");`
`return await Connection.QueryAsync<ObrMaestroObra>(new CommandDefinition(query.ToString(), parameters));`

ObrMaestroObra is the entity generated, but i have to add alias to column name for successfull mapping.

`public class ObrMaestroObra : IEntity
	{
		public ObrMaestroObra()
		{
		}

		public ObrMaestroObra(string obraidcontenido)
		{
			ObraIdContenido = obraidcontenido;
		}

		public string ObraIdContenido { get; set; }

		public string ObraTitulo { get; set; }

		public bool? ObraEsRecomendado { get; set; }

		public int? ObraOrdenRecomendado { get; set; }

		public bool? ObraEsVisible { get; set; }`

I dont know if you undestand me... Thanks

**Comment by hherzl** [comment]
Hi, get last version and try again, let me know if you have any issues.

Regards

**Comment by GetDragon** [comment]
Thanks bro...
